Add diagnostic for "ValueError: max() arg is an empty sequence" error
nlohmann/cmake_min_version pull request #11
Opened 2023-07-23 21:04 UTC by jeremy-rifkin

If you run the script without first downloading cmake versions you get the following error:

```
› venv/bin/python cmake_min_version.py ~/path/to/project
Found 0 CMake binaries from directory tools

Traceback (most recent call last):
  File "<path>/cmake_min_version/cmake_min_version.py", line 162, in <module>
    working_version = binary_search(args.params, args.tools_directory)
  File "<path>/cmake_min_version/cmake_min_version.py", line 79, in binary_search
    longest_version_string = max([len(cmake.version) for cmake in versions]) + 1  # type: int
ValueError: max() arg is an empty sequence
```

This PR just adds a quick error to tell the user what to do.

2023-07-24 05:27 UTC, nlohmann requested changes

2023-07-24 05:27 UTC, nlohmann commented on cmake_min_version.py
> +        print(colored('Error: No cmake versions found in the tool dir. Make sure to run the cmake_downloader script first.', 'red'))
```suggestion
        print(colored('Error: No CMake versions found in the tool dir. Make sure to run the cmake_downloader script first.', 'red'))
```

2023-07-24 23:06 UTC, jeremy-rifkin commented
Thanks for taking a look!

2023-07-25 04:41 UTC, nlohmann approved these changes
Looks good to me.

2023-07-25 20:01 UTC, jeremy-rifkin commented
Yes!

2023-07-26 05:22 UTC, merged

2023-07-26 05:22 UTC, nlohmann commented
Thanks!